name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Authentification GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Installer gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: my-java-project-481220
          version: latest

      # 4️⃣ Configurer Docker pour Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      # 5️⃣ Télécharger l'artifact Java
      - name: Download Java artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app-jar
          path: ./build/libs

      # 6️⃣ Build et push Docker image
      - name: Build and Push Docker image
        env:
          IMAGE_URI: europe-west1-docker.pkg.dev/my-java-project-481220/java-repo/java-app:latest
        run: |
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
